components/Category/Navbar.vue, components/Checkout/AdyenExternalPaymentProvider.vue, components/Checkout/CartPreview.vue, components/Checkout/UserShippingAddresses.vue, components/Checkout/VsfPaymentProvider.vue, components/Checkout/VsfShippingProvider.vue, components/LoginModal.vue, components/MyAccount/OrderHistory.vue, components/RelatedProducts.vue, components/UserBillingAddress.vue, components/UserShippingAddress.vue, nuxt.config.js, pages/Checkout.vue, pages/Checkout/Billing.vue, pages/Checkout/Payment.vue, pages/Checkout/Shipping.vue, pages/Checkout/ThankYou.vue
[https://pm.odoogap.com/projects/vuestorefront-api/work_packages/12988/activity?query_id=641](https://pm.odoogap.com/projects/vuestorefront-api/work_packages/12988/activity?query_id=641)
=> [IMP] Update VSF Core version

components/WishlistSidebar.vue
[https://pm.odoogap.com/work_packages/14076/activity](https://pm.odoogap.com/work_packages/14076/activity)
=> [FIX] 14076-Wishlist-issues-solve

pages/Category.vue, pages/Product.vue
[https://pm.odoogap.com/work_packages/14070/activity](https://pm.odoogap.com/work_packages/14070/activity)
=> [FIX] 14070-Add-to-shopping-cart-should-open-the-cart

pages/Product.vue
[https://pm.odoogap.com/work_packages/14069/activity](https://pm.odoogap.com/work_packages/14069/activity)
=> [FIX] 14069-Qty-selector-should-work

composables/useUiHelpers/index.ts
[https://pm.odoogap.com/work_packages/13799/activity](https://pm.odoogap.com/work_packages/13799/activity)
=> [FIX] 13799-Show-on-page-should-work

assets/styles.scss, components/TopBar.vue
[https://pm.odoogap.com/work_packages/13265/activity](https://pm.odoogap.com/work_packages/13265/activity)
=> [FIX] 13265-Fix-style-on-cart

pages/Checkout/Shipping.vue
[https://pm.odoogap.com/projects/vuestorefront-api/work_packages/14237/activity?query_id=641](https://pm.odoogap.com/projects/vuestorefront-api/work_packages/14237/activity?query_id=641)
=> [FIX] Checkout go back

components/CartSidebar.vue, components/Checkout/AdyenDirectPaymentProvider.vue, components/Core/Atoms/OdooButton.vue, components/LoginModal.vue, components/MyAccount/ProfileUpdateForm.vue, components/MyAccount/ShippingAddressForm.vue, components/MyAccount/ShippingList.vue, package.json, pages/Cart.vue, pages/Checkout/Billing.vue, pages/Checkout/Payment.vue, pages/Checkout/Shipping.vue, pages/MyAccount.vue
Fix lint problems and update vsf/odoo version
=> Release v1.5.1

assets/styles.scss, composables/useUiHelpers/index.ts
https://pm.odoogap.com/work_packages/16039/activity
=> [FIX] 16039

components/CartSidebar.vue, components/WishlistSidebar.vue, composables/useUiHelpers/index.ts, pages/Cart.vue, pages/Category.vue, pages/Product.vue
https://pm.odoogap.com/work_packages/16036/activity
=> [IMP] 16036

composables/useUiHelpers/index.ts, pages/Checkout/Payment.vue
https://pm.odoogap.com/work_packages/16033/activity
=> [FIX] 16033

components/MyAccount/OrderHistory.vue, composables/useUiHelpers/index.ts, lang/en.json
https://pm.odoogap.com/work_packages/16029/activity
=> [FIX] 16029

composables/useUiHelpers/index.ts, lang/en.json
https://pm.odoogap.com/work_packages/16027/activity
=> [FIX] 16027

composables/useUiHelpers/index.ts, pages/Home.vue
https://pm.odoogap.com/work_packages/16023/activity
=> [FIX] 16023

composables/useUiHelpers/index.ts, pages/Home.vue
https://pm.odoogap.com/work_packages/16022/activity
=> [FIX] 16022

components/Category/Navbar.vue
https://pm.odoogap.com/work_packages/16042/activity
=> [FIX] Sort by doesn't work

middleware/checkout.js, pages/Checkout/Shipping.vue
https://pm.odoogap.com/work_packages/16038/activity
=> [FIX] Billing link

components/Category/FilterSideBar.vue, components/Category/Navbar.vue, composables/useUiHelpers/index.ts
https://pm.odoogap.com/work_packages/16043/activity
=> [FIX] Filters not working

assets/css/product.scss, assets/styles.scss, pages/Category.vue, pages/Product.vue
https://pm.odoogap.com/work_packages/16040/activity
=> [FIX] 16040 - No product image

composables/useUiHelpers/index.ts
https://pm.odoogap.com/work_packages/16163/activity
=> [FIX] 16163 - Pagination does not work

components/LocaleSelector.vue
https://pm.odoogap.com/work_packages/16041/activity
=> [FIX] 16041

components/Checkout/VsfShippingProvider.vue
https://pm.odoogap.com/work_packages/16193/activity
=> [FIX] 16193

components/AppFooter.vue
https://pm.odoogap.com/work_packages/16196/activity
=> [IMP] 16196

components/AppFooter.vue
https://pm.odoogap.com/work_packages/16197/activity
=> [IMP] 16197

pages/Checkout/Billing.vue
https://pm.odoogap.com/work_packages/16194/activity
=> [IMP] 16194

components/WishlistSidebar.vue
https://pm.odoogap.com/work_packages/16198/activity
=> [FIX] 16198

components/AppHeader.vue
https://pm.odoogap.com/work_packages/16024/activity
=> [FIX] 16024

components/Checkout/CartPreview.vue, middleware/checkout.js, pages/Cart.vue, pages/Checkout/Billing.vue, pages/Checkout/Shipping.vue
https://pm.odoogap.com/work_packages/16038/activity
=> [FIX] 16038

components/AppFooter.vue
https://pm.odoogap.com/work_packages/16170/activity
=> [IMP] 16170

assets/styles.scss, components/MyAccount/PasswordResetForm.vue, components/MyAccount/ProfileUpdateForm.vue, components/MyAccount/ShippingAddressForm.vue, pages/Checkout/Billing.vue, pages/Checkout/Shipping.vue
https://pm.odoogap.com/work_packages/16026/activity
=> [FIX] [CHECKOUT & MY ACCOUNT] - Address fields

pages/Cart.vue
https://pm.odoogap.com/projects/vuestorefront-api/work_packages/16244/activity?query_id=641
=> [FIX] 16244

components/CartSidebar.vue, components/WishlistSidebar.vue
https://pm.odoogap.com/projects/vuestorefront-api/work_packages/16245/activity?query_id=641
=> [FIX] 16245

components/AppHeader.vue, layouts/default.vue, pages/Category.vue
https://pm.odoogap.com/projects/vuestorefront-api/work_packages/16233/activity?query_id=641
=> [FIX] 16233

layouts/default.vue, pages/Category.vue
https://pm.odoogap.com/projects/vuestorefront-api/work_packages/16168/activity?query_id=641
=> [FIX] 16168

components/SearchResults.vue
https://pm.odoogap.com/projects/vuestorefront-api/work_packages/16242/activity?query_id=641
=> [FIX] 16242

components/CartSidebar.vue, components/WishlistSidebar.vue, pages/Cart.vue
https://pm.odoogap.com/projects/vuestorefront-api/work_packages/16243/activity?query_id=641
=> [FIX] 16243
